/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Model.Attraction;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JScrollPane;
import javax.swing.JSpinner;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author andrewc4
 */
public class AttractionView extends javax.swing.JPanel {

    /**
     * Creates new form AttractionView
     */
public AttractionView(ArrayList<Attraction> attList) {
        initComponents();
        populateTable(attList);
    }
    public void populateTable(ArrayList<Attraction> attList){
        DefaultTableModel model =  (DefaultTableModel) attractionTable.getModel();
        Object rowData[] = new Object[5];
        for(int i = 0; i < attList.size(); i++){
       
            rowData[0] = attList.get(i).getAttractionID();
            rowData[1] = attList.get(i).getName();
            rowData[2] = attList.get(i).getDescription();
            rowData[3] = attList.get(i).getMaxCapacity();
            rowData[4] = attList.get(i).getWaitTime();
            model.addRow(rowData);
       }     
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        attractionTable = new javax.swing.JTable();
        scheduleBtn = new javax.swing.JButton();
        partySpinner = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        attractionTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Description ", "Max. Capacity", "Wait Time"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        attractionTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(attractionTable);
        if (attractionTable.getColumnModel().getColumnCount() > 0) {
            attractionTable.getColumnModel().getColumn(0).setResizable(false);
            attractionTable.getColumnModel().getColumn(1).setResizable(false);
            attractionTable.getColumnModel().getColumn(2).setResizable(false);
            attractionTable.getColumnModel().getColumn(3).setResizable(false);
            attractionTable.getColumnModel().getColumn(4).setResizable(false);
        }

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 47, 1000, 450));

        scheduleBtn.setText("Schedule");
        scheduleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scheduleBtnActionPerformed(evt);
            }
        });
        add(scheduleBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 520, 110, 40));

        partySpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));
        add(partySpinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 520, -1, 40));

        jLabel1.setText("Party Size:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 530, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void scheduleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scheduleBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_scheduleBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable attractionTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSpinner partySpinner;
    private javax.swing.JButton scheduleBtn;
    // End of variables declaration//GEN-END:variables

    public JTable getAttractionTable() {
        return attractionTable;
    }

    public void setAttractionTable(JTable attractionTable) {
        this.attractionTable = attractionTable;
    }

    public JScrollPane getjScrollPane3() {
        return jScrollPane3;
    }

    public void setjScrollPane3(JScrollPane jScrollPane3) {
        this.jScrollPane3 = jScrollPane3;
    }

    public JSpinner getPartySpinner() {
        return partySpinner;
    }

    public void setPartySpinner(JSpinner partySpinner) {
        this.partySpinner = partySpinner;
    }

    public JButton getScheduleBtn() {
        return scheduleBtn;
    }

    public void setScheduleBtn(JButton scheduleBtn) {
        this.scheduleBtn = scheduleBtn;
    }




}
