/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import javax.swing.JButton;
import javax.swing.JToggleButton;

/**
 *
 * @author andrewc4
 */
public class NavigationView extends javax.swing.JFrame {

    /**
     * Creates new form NavigationView
     */
    public NavigationView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        purchaseButton = new javax.swing.JToggleButton();
        orderBtn = new javax.swing.JButton();
        reserveBtn = new javax.swing.JButton();
        schAttBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        purchaseButton.setText("Purchase Tickets");
        purchaseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purchaseButtonActionPerformed(evt);
            }
        });
        getContentPane().add(purchaseButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, -1, -1));

        orderBtn.setText("Order Food");
        orderBtn.setEnabled(false);
        getContentPane().add(orderBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 260, -1, -1));

        reserveBtn.setText("Reservations");
        reserveBtn.setEnabled(false);
        getContentPane().add(reserveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 260, -1, -1));

        schAttBtn.setText("Schedule Attractions");
        schAttBtn.setEnabled(false);
        getContentPane().add(schAttBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 260, -1, -1));

        setSize(new java.awt.Dimension(1070, 628));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void purchaseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purchaseButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_purchaseButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NavigationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NavigationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NavigationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NavigationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NavigationView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton orderBtn;
    private javax.swing.JToggleButton purchaseButton;
    private javax.swing.JButton reserveBtn;
    private javax.swing.JButton schAttBtn;
    // End of variables declaration//GEN-END:variables

    public JToggleButton getPurchaseButton() {
        return purchaseButton;
    }

    public void setPurchaseButton(JToggleButton purchaseButton) {
        this.purchaseButton = purchaseButton;
    }

    public JButton getSchAttBtn() {
        return schAttBtn;
    }

    public void setSchAttBtn(JButton schAttBtn) {
        this.schAttBtn = schAttBtn;
    }



    public JButton getOrderBtn() {
        return orderBtn;
    }

    public void setOrderBtn(JButton orderBtn) {
        this.orderBtn = orderBtn;
    }

    public JButton getReserveBtn() {
        return reserveBtn;
    }

    public void setReserveBtn(JButton reserveBtn) {
        this.reserveBtn = reserveBtn;
    }
    
}
