/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Model.Attraction;
import Model.SitDownReservation;
import Model.UserAccount;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author andrewc4
 */
public class ProfileView extends javax.swing.JPanel {

    /**
     * Creates new form ProfileView
     */
    public ProfileView(ArrayList<Attraction> schedule, ArrayList<SitDownReservation> reservations, UserAccount activeUser) {
        initComponents();
        userName.setText(activeUser.getName());
        userEmail.setText(activeUser.getEmail());
        userDOB.setText(activeUser.getDateOfBirth());
        populateAttractionTable(schedule);
        populateReservationTable(reservations);
    }

    public ProfileView(){}
    
    public void populateAttractionTable(ArrayList<Attraction> schAttList){
        DefaultTableModel model =  (DefaultTableModel) attractionScheduleTable.getModel();
        Object rowData[] = new Object[5];
        for(int i = 0; i < schAttList.size(); i++){
       
            rowData[0] = schAttList.get(i).getName();
            rowData[1] = schAttList.get(i).getWaitTime();
            rowData[2] = schAttList.get(i).getPartySize(); // <-- Party Size
            
            model.addRow(rowData);
       }
    }
    
    public void populateReservationTable(ArrayList<SitDownReservation> schResList){
        DefaultTableModel model =  (DefaultTableModel) reservationScheduleTable.getModel();
        Object rowData[] = new Object[5];
        for(int i = 0; i < schResList.size(); i++){
       
            rowData[0] = schResList.get(i).getScheduledVendor().getName();
            rowData[1] = schResList.get(i).getScheduledVendor().getLocation();
            rowData[2] = schResList.get(i).getTime();
            
            model.addRow(rowData);
       }
     
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userName = new javax.swing.JLabel();
        userEmail = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        attractionScheduleTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        reservationScheduleTable = new javax.swing.JTable();
        userDOB = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        viewTicketButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userName.setText("jLabel1");
        add(userName, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 55, -1, -1));

        userEmail.setText("jLabel2");
        add(userEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 92, -1, -1));

        attractionScheduleTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Wait Time", "Party Size"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(attractionScheduleTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 193, 417, 331));

        reservationScheduleTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Location", "Time"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(reservationScheduleTable);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(501, 193, 417, 331));

        userDOB.setText("jLabel3");
        add(userDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 130, -1, -1));

        jLabel4.setText("Scheduled Attraction");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 171, -1, -1));

        jLabel5.setText("Reservations");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(682, 171, -1, -1));

        viewTicketButton.setText("View Ticket");
        viewTicketButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewTicketButtonActionPerformed(evt);
            }
        });
        add(viewTicketButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(682, 89, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void viewTicketButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewTicketButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewTicketButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable attractionScheduleTable;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable reservationScheduleTable;
    private javax.swing.JLabel userDOB;
    private javax.swing.JLabel userEmail;
    private javax.swing.JLabel userName;
    private javax.swing.JButton viewTicketButton;
    // End of variables declaration//GEN-END:variables

    public JTable getAttractionScheduleTable() {
        return attractionScheduleTable;
    }

    public void setAttractionScheduleTable(JTable attractionScheduleTable) {
        this.attractionScheduleTable = attractionScheduleTable;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JScrollPane getjScrollPane2() {
        return jScrollPane2;
    }

    public void setjScrollPane2(JScrollPane jScrollPane2) {
        this.jScrollPane2 = jScrollPane2;
    }

    public JTable getReservationScheduleTable() {
        return reservationScheduleTable;
    }

    public void setReservationScheduleTable(JTable reservationScheduleTable) {
        this.reservationScheduleTable = reservationScheduleTable;
    }

    public JLabel getUserDOB() {
        return userDOB;
    }

    public void setUserDOB(JLabel userDOB) {
        this.userDOB = userDOB;
    }

    public JLabel getUserEmail() {
        return userEmail;
    }

    public void setUserEmail(JLabel userEmail) {
        this.userEmail = userEmail;
    }

    public JLabel getUserName() {
        return userName;
    }

    public void setUserName(JLabel userName) {
        this.userName = userName;
    }

    public JButton getViewTicketButton() {
        return viewTicketButton;
    }

    public void setViewTicketButton(JButton viewTicketButton) {
        this.viewTicketButton = viewTicketButton;
    }

    
}
