/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Model.Attraction;
import Model.SitDownFoodVendor;
import com.github.lgooddatepicker.components.DatePicker;
import java.util.ArrayList;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JScrollPane;
import javax.swing.JSpinner;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author andrewc4
 */
public class ReservationView extends javax.swing.JPanel {

    /**
     * Creates new form ReservationView
     */
    public ReservationView(ArrayList<SitDownFoodVendor> restList, ArrayList<String> dateList) {
        initComponents();
        populateDateBox(dateList);
        populateTable(restList);
    }

    public void populateTable(ArrayList<SitDownFoodVendor> restList) {
        DefaultTableModel model = (DefaultTableModel) restTbl.getModel();
        Object rowData[] = new Object[4];
        for (int i = 0; i < restList.size(); i++) {

            rowData[0] = restList.get(i).getName();
            rowData[1] = restList.get(i).getLocation();
            rowData[2] = restList.get(i).getHours();
            rowData[3] = restList.get(i).getPrice();
            model.addRow(rowData);
        }

    }
    
    public void populateDateBox(ArrayList<String> dateList){
    
    dateBox.setModel(new DefaultComboBoxModel<>(dateList.toArray(new String[dateList.size()])));
    }

    public void populateComboBox(SitDownFoodVendor selectedRest) {
        timeBox.setModel(new DefaultComboBoxModel<>(selectedRest.getReservationTimes().toArray(new String[selectedRest.getReservationTimes().size()])));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        restTbl = new javax.swing.JTable();
        timeBox = new javax.swing.JComboBox<>();
        menuBtn = new javax.swing.JButton();
        reserveBtn = new javax.swing.JButton();
        restSpinner = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        dateBox = new javax.swing.JComboBox<>();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        restTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Location", "Hours ", "Cost"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        restTbl.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        restTbl.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        restTbl.getTableHeader().setReorderingAllowed(false);
        restTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                restTblMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(restTbl);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 47, 1000, 450));

        timeBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));
        timeBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeBoxActionPerformed(evt);
            }
        });
        add(timeBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 520, -1, 40));

        menuBtn.setText("View Menu");
        add(menuBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 520, -1, 40));

        reserveBtn.setText("Schedule Reservation ");
        reserveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reserveBtnActionPerformed(evt);
            }
        });
        add(reserveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 520, -1, 40));

        restSpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));
        add(restSpinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 520, -1, 40));

        jLabel1.setText("Dates Available:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 530, -1, -1));

        jLabel2.setText("Time:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 530, -1, -1));

        jLabel3.setText("Party Size:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 530, -1, -1));

        dateBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        dateBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateBoxActionPerformed(evt);
            }
        });
        add(dateBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 520, -1, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void timeBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timeBoxActionPerformed

    private void restTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_restTblMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_restTblMouseClicked

    private void reserveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reserveBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reserveBtnActionPerformed

    private void dateBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> dateBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton menuBtn;
    private javax.swing.JButton reserveBtn;
    private javax.swing.JSpinner restSpinner;
    private javax.swing.JTable restTbl;
    private javax.swing.JComboBox<String> timeBox;
    // End of variables declaration//GEN-END:variables

    public JScrollPane getjScrollPane3() {
        return jScrollPane3;
    }

    public void setjScrollPane3(JScrollPane jScrollPane3) {
        this.jScrollPane3 = jScrollPane3;
    }

    public JButton getMenuBtn() {
        return menuBtn;
    }

    public void setMenuBtn(JButton menuBtn) {
        this.menuBtn = menuBtn;
    }

    public JSpinner getRestSpinner() {
        return restSpinner;
    }

    public void setRestSpinner(JSpinner restSpinner) {
        this.restSpinner = restSpinner;
    }

    public JButton getReserveBtn() {
        return reserveBtn;
    }

    public void setReserveBtn(JButton reserveBtn) {
        this.reserveBtn = reserveBtn;
    }

    public JComboBox<String> getDateBox() {
        return dateBox;
    }

    public void setDateBox(JComboBox<String> dateBox) {
        this.dateBox = dateBox;
    }



    public JTable getRestTbl() {
        return restTbl;
    }

    public void setRestTbl(JTable restTbl) {
        this.restTbl = restTbl;
    }

    public JComboBox<String> getTimeBox() {
        return timeBox;
    }

    public void setTimeBox(JComboBox<String> timeBox) {
        this.timeBox = timeBox;
    }

}
